services:
  - type: web
    name: duet-dating
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true 